name: Python Coverage

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  python-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest==8.4.1 coverage==7.9 pytest-cov==6.2.1

      - name: Run tests and generate coverage details
        run: |
          pytest --cov=src --cov-report=term
          coverage report -m
          # Opcional pero recomendado para acciones que leen XML:
          coverage xml -o coverage.xml

      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 70
          # Si tu acción exige ruta XML, se detecta por defecto "coverage.xml".
          # Si la quieres fijar explícitamente, descomenta la siguiente línea:
          # COVERAGE_PATH: coverage.xml

      - name: Fail if below threshold
        run: coverage report --fail-under=90
